[build]
    functions="functions"

[[redirects]]
    to="/.netlify/functions/app"
    from="/*"
    status=200

[context.branch-deploy.environment]
    process.env.ROOT_API = 'https://cosmos-odyssey.azurewebsites.net/api/v1.0/TravelPrices';